# Generated by Django 5.1.6 on 2025-03-20 05:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=1000)),
                ('brandname', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=10)),
                ('size', models.IntegerField(default=3)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField(default=0)),
                ('status', models.CharField(default='Packing', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('cart_date', models.DateField(default=datetime.datetime.now)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login')),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('isapprove', models.BooleanField(default=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.CharField(default='pending', max_length=255)),
                ('order_status', models.CharField(default='ordered', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='Packing', max_length=50)),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
