# Generated by Django 5.1.6 on 2025-03-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0002_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='Login_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login'),
            preserve_default=False,
        ),
    ]
