# Generated by Django 5.1.6 on 2025-03-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0003_passwordreset_login_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='Login_details',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.login'),
        ),
    ]
